LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := EDM_UART
LOCAL_SRC_FILES := EDM_UART.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform

LOCAL_SHARED_LIBRARIES := serialport
LOCAL_REQUIRED_MODULES := serialport

include $(BUILD_PREBUILT)
include $(call all-makefiles-under,$(LOCAL_PATH))
